### ISSUE TITLE
Can we have cli entrance as bin by building to be used in python

### ISSUE THREAD

**Issue by cw1427** [robinjoseph08/redisqueue#12]
Can we have cli entrance as bin by building to be used in python?

**Comment by renta** [comment]
Redisqueue is a library. From my point of view, it should not have any bin files in it. You can write your own program using any of these tools https://github.com/renta/awesome-go#command-line and use Redisqueue inside it.

**Comment by robinjoseph08** [comment]
I agree with @renta. Creating a binary is out of the scope of this package. You can either build your own or just use the `redis-cli` to interact with the streams directly.
